import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut,createUserWithEmailAndPassword,initializeAuth}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,collection,getDocs,getDoc,doc,addDoc,setDoc,updateDoc,deleteDoc,serverTimestamp,runTransaction,writeBatch,query,orderBy,limit}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCTLUXUO1AraBgH3WO4e0izSnY319lWNyQ",authDomain:"lbs-peminjaman.firebaseapp.com",projectId:"lbs-peminjaman",storageBucket:"lbs-peminjaman.firebasestorage.app",messagingSenderId:"1036341632994",appId:"1:1036341632994:web:879fec5848a7f523d3e3bb"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
let currentUser=null,currentProfile=null,products=[],categories=[],transactions=[],opnames=[],detailsCache={};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=n=>Number(n||0).toLocaleString("id-ID",{maximumFractionDigits:3});
const dt=v=>{if(!v)return"-";if(v.toDate)return v.toDate().toLocaleString("id-ID");return new Date(v).toLocaleString("id-ID")};
function toast(s){$("toast").textContent=s;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2500)}
function openModal(html){$("modalContent").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden");$("modalContent").innerHTML=""}
$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
$("menuBtn").onclick=()=>$("sidebar")?.classList.toggle("open");
$("loginBtn").onclick=async()=>{ $("loginError").textContent="";try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(e){$("loginError").textContent="Login gagal. Periksa email/password."}};
$("logoutBtn").onclick=()=>signOut(auth);

async function loadProducts(){products=(await getDocs(collection(db,"products"))).docs.map(x=>({id:x.id,...x.data()}));}
async function loadCategories(){categories=(await getDocs(collection(db,"categories"))).docs.map(x=>({id:x.id,...x.data()}));}
async function loadTransactions(){transactions=(await getDocs(collection(db,"stock_transactions"))).docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>dt(b.createdAt).localeCompare(dt(a.createdAt)));}
async function loadOpnames(){opnames=(await getDocs(collection(db,"opnames"))).docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>dt(b.createdAt).localeCompare(dt(a.createdAt)));}

function nav(page){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("pageTitle").textContent={dashboard:"Dashboard",products:"Master Produk",inventory:"Inventory",transactions:"Stok Masuk/Keluar",opname:"Stok Opname",reports:"Laporan",users:"Pengguna"}[page]||page;$("content").innerHTML="";({dashboard:renderDashboard,products:renderProducts,inventory:renderInventory,transactions:renderTransactions,opname:renderOpname,reports:renderReports,users:renderUsers}[page]||renderDashboard)();$("sidebar")?.classList.remove("open")}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>nav(n.dataset.page));

async function renderDashboard(){
 await loadProducts();await loadTransactions();await loadOpnames();
 const total=products.length,stok=products.reduce((a,p)=>a+Number(p.stok||0),0),aktif=products.filter(p=>p.aktif!==false).length;
 $("content").innerHTML=`<div class="stats">
 <div class="card stat">Total Produk<b>${total}</b></div><div class="card stat">Produk Aktif<b>${aktif}</b></div>
 <div class="card stat">Total Stok<b>${money(stok)}</b></div><div class="card stat">Stok Opname<b>${opnames.length}</b></div></div>
 <div class="card chart-card" style="margin-top:15px"><div class="dashboard-head"><div><h3>📊 Grafik Stok Semua Produk</h3><p class="small">Menampilkan stok terkini seluruh produk.</p></div></div><div class="chart-wrap"><canvas id="stockChart"></canvas></div></div>
 <div class="grid"><div class="card"><h3>📦 Master Produk</h3><p>Kelola kode, barcode, kategori, satuan, berat dan stok awal.</p><button class="btn primary" onclick="nav('products')">Buka Produk</button></div>
 <div class="card"><h3>📊 Inventory</h3><p>Lihat stok terkini dan lakukan stok masuk/keluar.</p><button class="btn primary" onclick="nav('inventory')">Buka Inventory</button></div>
 <div class="card"><h3>📝 Stok Opname</h3><p>Bandingkan stok sistem dengan stok fisik dan finalisasi penyesuaian.</p><button class="btn primary" onclick="nav('opname')">Buka Opname</button></div>
 <div class="card"><h3>📄 Laporan</h3><p>Export Excel dan PDF Berita Acara Stok Opname.</p><button class="btn primary" onclick="nav('reports')">Buka Laporan</button></div></div>
 <div class="card" style="margin-top:15px"><h3>Transaksi Terakhir</h3>${transactionTable(transactions.slice(0,8))}</div>`;
 const canvas=document.getElementById('stockChart');
 if(canvas && window.Chart){
   const sorted=[...products].sort((a,b)=>Number(b.stok||0)-Number(a.stok||0));
   new Chart(canvas,{type:'bar',data:{labels:sorted.map(p=>p.kodeProduk||p.namaProduk||'Produk'),datasets:[{label:'Stok',data:sorted.map(p=>Number(p.stok||0))}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:(c)=>`Stok: ${Number(c.raw||0).toLocaleString('id-ID')}`}}},scales:{x:{ticks:{autoSkip:false,maxRotation:45,minRotation:0}},y:{beginAtZero:true,ticks:{precision:0}}}}});
 }
}
function transactionTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Produk</th><th>Jenis</th><th>Qty</th><th>Sebelum</th><th>Sesudah</th><th>User</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${dt(t.createdAt)}</td><td>${esc(t.namaProduk)}</td><td><span class="badge">${t.type==="in"?"MASUK":t.type==="out"?"KELUAR":"ADJUSTMENT"}</span></td><td>${money(t.qty)}</td><td>${money(t.stokSebelum)}</td><td>${money(t.stokSesudah)}</td><td>${esc(t.userName)}</td></tr>`).join("")||"<tr><td colspan=7>Belum ada transaksi</td></tr>"}</tbody></table></div>`}

function renderProducts(){
 const admin=currentProfile.role==="admin";
 $("content").innerHTML=`<div class="card"><div class="toolbar"><div><h3>Master Produk</h3><p class="small">Data produk tersimpan di Firestore.</p></div><div class="actions">${admin?'<button class="btn primary" id="addProduct">+ Tambah Produk</button>':''}<button class="btn" id="scanProduct">📷 Scan Barcode</button><input id="productSearch" class="search" placeholder="Cari kode/barcode/nama..."></div></div><div id="productTable"></div></div>`;
 $("productSearch").oninput=()=>drawProducts($("productSearch").value);drawProducts("");
 if(admin)$("addProduct").onclick=()=>productForm();
 $("scanProduct").onclick=()=>scanBarcode(code=>{$("productSearch").value=code;drawProducts(code)});
}
function drawProducts(q){q=q.toLowerCase();let rows=products.filter(p=>[p.barcode,p.kodeProduk,p.namaProduk,p.kategori].some(x=>String(x||"").toLowerCase().includes(q)));$("productTable").innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Barcode</th><th>Kode</th><th>Nama</th><th>Kategori</th><th>Stok</th><th>Satuan</th><th>Lokasi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.barcode)}</td><td>${esc(p.kodeProduk)}</td><td>${esc(p.namaProduk)}</td><td>${esc(p.kategori)}</td><td>${money(p.stok)}</td><td>${esc(p.satuan)}</td><td>${esc(p.lokasi)}</td><td>${p.aktif===false?"Nonaktif":"Aktif"}</td><td>${currentProfile.role==="admin"?`<button class="btn" onclick="productForm('${p.id}')">Edit</button> <button class="btn red" onclick="removeProduct('${p.id}')">Hapus</button>`:"-"}</td></tr>`).join("")||"<tr><td colspan=9>Tidak ada data</td></tr>"}</tbody></table></div>`}
window.productForm=async id=>{let p=id?products.find(x=>x.id===id):{};await loadCategories();openModal(`<h2>${id?"Edit":"Tambah"} Produk</h2><form id="productForm"><div class="form-grid">
${field("barcode","Barcode",p.barcode||"","required")} ${field("kodeProduk","Kode Produk",p.kodeProduk||"","required")}
${field("namaProduk","Nama Produk",p.namaProduk||"","required")} <div class="form-group"><label>Kategori</label><input name="kategori" list="cats" value="${esc(p.kategori||"")}" required><datalist id="cats">${categories.map(c=>`<option value="${esc(c.nama||c.id)}">`).join("")}</datalist></div>
${field("satuan","Satuan",p.satuan||"Bag","required")} ${field("beratPerSatuan","Berat / Satuan",p.beratPerSatuan??1,"required","number","0.001")}
${field("stok","Stok",p.stok??0,"required","number","0.001")} ${field("stokLbs","Stok LBS",p.stokLbs??0,"","number","0.001")}
${field("lokasi","Lokasi",p.lokasi||"Cold Storage")} <div class="form-group"><label>Status</label><select name="aktif"><option value="true" ${p.aktif!==false?"selected":""}>Aktif</option><option value="false" ${p.aktif===false?"selected":""}>Nonaktif</option></select></div>
</div><div class="actions"><button class="btn primary">Simpan</button></div></form>`);
$("productForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),d={barcode:f.get("barcode").trim(),kodeProduk:f.get("kodeProduk").trim(),namaProduk:f.get("namaProduk").trim(),kategori:f.get("kategori").trim(),satuan:f.get("satuan").trim(),beratPerSatuan:Number(f.get("beratPerSatuan")),stok:Number(f.get("stok")),stokLbs:Number(f.get("stokLbs")),lokasi:f.get("lokasi").trim(),aktif:f.get("aktif")==="true",updatedAt:serverTimestamp()};try{id?await updateDoc(doc(db,"products",id),d):await addDoc(collection(db,"products"),{...d,createdAt:serverTimestamp()});closeModal();toast("Produk tersimpan");renderProducts()}catch(err){alert("Gagal menyimpan: "+err.message)}}}
window.removeProduct=async id=>{if(!confirm("Hapus produk ini?"))return;await deleteDoc(doc(db,"products",id));toast("Produk dihapus");renderProducts()}
function field(n,l,v,req="",type="text",step=""){return `<div class="form-group"><label>${l}</label><input name="${n}" type="${type}" value="${esc(v)}" ${req} ${step?`step="${step}"`:""}></div>`}

async function renderInventory(){await loadProducts();$("content").innerHTML=`<div class="card"><div class="toolbar"><div><h3>Inventory</h3><p class="small">Stok terkini seluruh produk.</p></div><input id="invSearch" class="search" placeholder="Cari produk..."></div><div id="invTable"></div></div>`;drawInv("");$("invSearch").oninput=e=>drawInv(e.target.value)}
function drawInv(q){q=q.toLowerCase();let rows=products.filter(p=>[p.barcode,p.kodeProduk,p.namaProduk,p.kategori].some(x=>String(x||"").toLowerCase().includes(q)));$("invTable").innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Barcode</th><th>Stok</th><th>Satuan</th><th>LBS</th><th>Lokasi</th><th>Aksi</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.kodeProduk)}</td><td>${esc(p.namaProduk)}</td><td>${esc(p.barcode)}</td><td><b>${money(p.stok)}</b></td><td>${esc(p.satuan)}</td><td>${money(p.stokLbs)}</td><td>${esc(p.lokasi)}</td><td><button class="btn green" onclick="stockForm('${p.id}','in')">+ Masuk</button> <button class="btn red" onclick="stockForm('${p.id}','out')">− Keluar</button></td></tr>`).join("")||"<tr><td colspan=8>Tidak ada data</td></tr>"}</tbody></table></div>`}
window.stockForm=async(id,type)=>{let p=products.find(x=>x.id===id);openModal(`<h2>Stok ${type==="in"?"Masuk":"Keluar"}</h2><div class="notice"><b>${esc(p.namaProduk)}</b><br>Stok saat ini: ${money(p.stok)} ${esc(p.satuan)}</div><form id="stockForm">${field("qty","Jumlah",1,"required","number","0.001")}${field("keterangan","Keterangan","","")}</form><div class="actions"><button class="btn primary" id="saveStock">Simpan</button></div>`);
$("saveStock").onclick=async()=>{let qty=Number($('stockForm').querySelector('[name=qty]').value),ket=$('stockForm').querySelector('[name=keterangan]').value.trim();if(qty<=0)return alert("Jumlah harus lebih dari 0");try{await runTransaction(db,async tx=>{let ref=doc(db,"products",id),snap=await tx.get(ref);if(!snap.exists())throw Error("Produk tidak ditemukan");let d=snap.data(),before=Number(d.stok||0),after=type==="in"?before+qty:before-qty;if(after<0)throw Error("Stok tidak mencukupi");let tr=doc(collection(db,"stock_transactions"));tx.update(ref,{stok:after,updatedAt:serverTimestamp()});tx.set(tr,{productId:id,barcode:d.barcode||"",kodeProduk:d.kodeProduk||"",namaProduk:d.namaProduk||"",type,qty,stokSebelum:before,stokSesudah:after,keterangan:ket,userId:currentUser.uid,userName:currentProfile.nama||currentUser.email,createdAt:serverTimestamp()})});closeModal();toast("Transaksi berhasil");renderInventory()}catch(e){alert("Gagal: "+e.message)}}}

async function renderTransactions(){await loadTransactions();$("content").innerHTML=`<div class="card"><div class="toolbar"><div><h3>Riwayat Stok</h3></div><button class="btn blue" id="exportTrx">Export Excel</button></div>${transactionTable(transactions)}</div>`;$("exportTrx").onclick=()=>exportExcel(transactions.map(t=>({Tanggal:dt(t.createdAt),Kode:t.kodeProduk,Nama:t.namaProduk,Barcode:t.barcode,Jenis:t.type,Qty:t.qty,Sebelum:t.stokSebelum,Sesudah:t.stokSesudah,Keterangan:t.keterangan,User:t.userName})), "Riwayat_Stok")}
async function renderOpname(){await loadProducts();await loadOpnames();$("content").innerHTML=`<div class="card"><div class="toolbar"><div><h3>Stok Opname</h3><p class="small">Buat opname, masukkan stok fisik, lalu finalisasi.</p></div><button class="btn primary" id="newOpname">+ Opname Baru</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Nomor</th><th>Tanggal</th><th>Lokasi</th><th>Status</th><th>User</th><th>Aksi</th></tr></thead><tbody>${opnames.map(o=>`<tr><td>${esc(o.nomor)}</td><td>${dt(o.tanggal||o.createdAt)}</td><td>${esc(o.lokasi)}</td><td>${esc(o.status)}</td><td>${esc(o.createdByName)}</td><td><button class="btn" onclick="openOpname('${o.id}')">Buka</button> ${o.status==="draft"?`<button class="btn blue" onclick="finalizeOpname('${o.id}')">Finalisasi</button>`:""}</td></tr>`).join("")||"<tr><td colspan=6>Belum ada opname</td></tr>"}</tbody></table></div></div>`;$("newOpname").onclick=newOpname}
async function newOpname(){let nomor="BA-SO-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(opnames.length+1).padStart(3,"0");openModal(`<h2>Opname Baru</h2><form id="opForm"><div class="form-grid">${field("nomor","Nomor",nomor,"required")}${field("tanggal","Tanggal",new Date().toISOString().slice(0,10),"required","date")}${field("lokasi","Lokasi","Cold Storage")}</div><div class="actions"><button class="btn primary">Buat Opname</button></div></form>`);$("opForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);let ref=await addDoc(collection(db,"opnames"),{nomor:f.get("nomor"),tanggal:f.get("tanggal"),lokasi:f.get("lokasi"),status:"draft",createdBy:currentUser.uid,createdByName:currentProfile.nama||currentUser.email,createdAt:serverTimestamp()});for(const p of products){await setDoc(doc(db,"opnames",ref.id,"details",p.id),{productId:p.id,barcode:p.barcode||"",kodeProduk:p.kodeProduk||"",namaProduk:p.namaProduk||"",satuan:p.satuan||"",systemStock:Number(p.stok||0),physicalStock:Number(p.stok||0),difference:0,note:""})}closeModal();toast("Opname dibuat");renderOpname()}}
window.openOpname=async id=>{let o=opnames.find(x=>x.id===id);let snap=await getDocs(collection(db,"opnames",id,"details"));let ds=snap.docs.map(x=>({id:x.id,...x.data()}));openModal(`<h2>Opname ${esc(o.nomor)}</h2><div class="notice">Tanggal: ${dt(o.tanggal)} · Lokasi: ${esc(o.lokasi)} · Status: <b>${esc(o.status)}</b></div><div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Sistem</th><th>Fisik</th><th>Selisih</th><th>Catatan</th></tr></thead><tbody>${ds.map(d=>`<tr><td>${esc(d.kodeProduk)}</td><td>${esc(d.namaProduk)}</td><td>${money(d.systemStock)}</td><td><input class="phys" data-id="${d.id}" type="number" step="0.001" value="${d.physicalStock}"></td><td id="dif-${d.id}" class="${d.difference<0?"negative":d.difference>0?"positive":""}">${money(d.difference)}</td><td><input class="note" data-id="${d.id}" value="${esc(d.note)}"></td></tr>`).join("")}</tbody></table></div>${o.status==="draft"?'<div class="actions"><button class="btn primary" id="saveOp">Simpan Fisik</button></div>':""}`);document.querySelectorAll(".phys").forEach(inp=>inp.oninput=()=>{let d=ds.find(x=>x.id===inp.dataset.id),dif=Number(inp.value)-Number(d.systemStock),el=$("dif-"+d.id);el.textContent=money(dif);el.className=dif<0?"negative":dif>0?"positive":""});if($("saveOp"))$("saveOp").onclick=async()=>{let batch=writeBatch(db);for(const d of ds){let phys=Number(document.querySelector(`.phys[data-id="${d.id}"]`).value),note=document.querySelector(`.note[data-id="${d.id}"]`).value.trim();batch.update(doc(db,"opnames",id,"details",d.id),{physicalStock:phys,difference:phys-Number(d.systemStock),note,updatedAt:serverTimestamp()})}await batch.commit();closeModal();toast("Stok fisik tersimpan");renderOpname()}}
window.finalizeOpname=async id=>{if(!confirm("Finalisasi akan mengubah stok sistem menjadi stok fisik. Lanjutkan?"))return;let o=opnames.find(x=>x.id===id),snap=await getDocs(collection(db,"opnames",id,"details")),ds=snap.docs.map(x=>({id:x.id,...x.data()}));let batch=writeBatch(db);for(const d of ds){if(Number(d.difference||0)!==0){let pref=doc(db,"products",d.productId),tref=doc(collection(db,"stock_transactions"));batch.update(pref,{stok:Number(d.physicalStock),updatedAt:serverTimestamp()});batch.set(tref,{productId:d.productId,barcode:d.barcode,kodeProduk:d.kodeProduk,namaProduk:d.namaProduk,type:"adjustment",qty:Math.abs(Number(d.difference)),selisih:Number(d.difference),stokSebelum:Number(d.systemStock),stokSesudah:Number(d.physicalStock),keterangan:"Penyesuaian Stok Opname "+o.nomor,userId:currentUser.uid,userName:currentProfile.nama||currentUser.email,createdAt:serverTimestamp()})}}batch.update(doc(db,"opnames",id),{status:"final",finalizedAt:serverTimestamp(),finalizedBy:currentUser.uid,finalizedByName:currentProfile.nama||currentUser.email});await batch.commit();toast("Opname berhasil difinalisasi");renderOpname()}

async function renderReports(){await loadProducts();await loadTransactions();await loadOpnames();$("content").innerHTML=`<div class="grid"><div class="card"><h3>📊 Laporan Inventory</h3><p>Download stok terkini dalam Excel.</p><button class="btn blue" id="exInv">Excel Inventory</button></div><div class="card"><h3>🔄 Laporan Transaksi</h3><p>Download seluruh riwayat stok.</p><button class="btn blue" id="exTrx">Excel Transaksi</button></div><div class="card"><h3>📝 Berita Acara Opname</h3><p>Pilih opname final/draft lalu cetak PDF.</p><select id="opSelect" style="padding:10px;width:100%;margin:10px 0"><option value="">Pilih opname</option>${opnames.map(o=>`<option value="${o.id}">${esc(o.nomor)} - ${esc(o.lokasi)}</option>`).join("")}</select><button class="btn primary" id="pdfOp">Download PDF</button></div></div>`;$("exInv").onclick=()=>exportExcel(products.map(p=>({Barcode:p.barcode,Kode:p.kodeProduk,Nama:p.namaProduk,Kategori:p.kategori,Stok:p.stok,Satuan:p.satuan,"Berat/Satuan":p.beratPerSatuan,"Stok LBS":p.stokLbs,Lokasi:p.lokasi,Status:p.aktif===false?"Nonaktif":"Aktif"})),"Inventory");$("exTrx").onclick=()=>exportExcel(transactions.map(t=>({Tanggal:dt(t.createdAt),Kode:t.kodeProduk,Nama:t.namaProduk,Jenis:t.type,Qty:t.qty,Sebelum:t.stokSebelum,Sesudah:t.stokSesudah,Keterangan:t.keterangan,User:t.userName})),"Transaksi");$("pdfOp").onclick=()=>{let id=$("opSelect").value;if(id)makeOpnamePDF(id);else alert("Pilih opname dulu")}}
function exportExcel(rows,name){if(!window.XLSX)return alert("Library Excel belum termuat");let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Data");XLSX.writeFile(wb,name+"_"+new Date().toISOString().slice(0,10)+".xlsx")}
async function makeOpnamePDF(id){let o=opnames.find(x=>x.id===id),snap=await getDocs(collection(db,"opnames",id,"details")),ds=snap.docs.map(x=>x.data()),{jsPDF}=window.jspdf;let pdf=new jsPDF("p","mm","a4");pdf.setFontSize(15);pdf.text("PT LAMPUNG BAY SEAFOOD",105,15,{align:"center"});pdf.setFontSize(13);pdf.text("BERITA ACARA STOK OPNAME",105,23,{align:"center"});pdf.setFontSize(10);pdf.text("Nomor: "+o.nomor,15,34);pdf.text("Tanggal: "+dt(o.tanggal),15,41);pdf.text("Lokasi: "+o.lokasi,15,48);pdf.autoTable({startY:55,head:[["No","Kode","Nama Produk","Sistem","Fisik","Selisih","Satuan"]],body:ds.map((d,i)=>[i+1,d.kodeProduk,d.namaProduk,d.systemStock,d.physicalStock,d.difference,d.satuan]),styles:{fontSize:8},headStyles:{halign:"center"}});let y=pdf.lastAutoTable.finalY+15;pdf.text("Demikian Berita Acara Stok Opname ini dibuat untuk dipergunakan sebagaimana mestinya.",15,y,{maxWidth:180});pdf.text("Mengetahui,",45,y+18,{align:"center"});pdf.text("Petugas Opname,",155,y+18,{align:"center"});pdf.text("(________________)",45,y+48,{align:"center"});pdf.text("("+ (o.createdByName||"") +")",155,y+48,{align:"center"});pdf.save(o.nomor+".pdf")}
async function renderUsers(){await loadCategories();let us=(await getDocs(collection(db,"users"))).docs.map(x=>({id:x.id,...x.data()}));$("content").innerHTML=`<div class="card"><div class="toolbar"><div><h3>Pengguna</h3><p class="small">Kelola profil role yang sudah memiliki akun Authentication.</p></div><button class="btn primary" id="newUser">+ Buat Operator</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Aktif</th><th>Aksi</th></tr></thead><tbody>${us.map(u=>`<tr><td>${esc(u.nama)}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${u.aktif?"Aktif":"Nonaktif"}</td><td><button class="btn" onclick="editUser('${u.id}')">Edit</button></td></tr>`).join("")}</tbody></table></div></div>`;$("newUser").onclick=newUser}
async function newUser(){openModal(`<h2>Buat Akun Operator</h2><div class="notice">Akun dibuat melalui Firebase Authentication, lalu profil operator disimpan ke Firestore.</div><form id="userForm"><div class="form-grid">${field("nama","Nama","","required")}${field("email","Email","","required","email")}${field("password","Password","","required","password")}</div><div class="actions"><button class="btn primary">Buat Akun</button></div></form>`);$("userForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{const secondary=initializeApp(firebaseConfig,"secondary-"+Date.now());const a2=getAuth(secondary);let cred=await createUserWithEmailAndPassword(a2,f.get("email"),f.get("password"));await setDoc(doc(db,"users",cred.user.uid),{nama:f.get("nama"),email:f.get("email"),role:"operator",aktif:true,createdAt:serverTimestamp()});await signOut(a2);closeModal();toast("Operator berhasil dibuat");renderUsers()}catch(err){alert("Gagal membuat operator: "+err.message)}}}
window.editUser=async id=>{let s=await getDoc(doc(db,"users",id)),u=s.data();openModal(`<h2>Edit Pengguna</h2><form id="editUser"><div class="form-grid">${field("nama","Nama",u.nama||"","required")}${field("email","Email",u.email||"","required","email")}<div class="form-group"><label>Role</label><select name="role"><option value="admin" ${u.role==="admin"?"selected":""}>Admin</option><option value="operator" ${u.role==="operator"?"selected":""}>Operator</option></select></div><div class="form-group"><label>Status</label><select name="aktif"><option value="true" ${u.aktif!==false?"selected":""}>Aktif</option><option value="false" ${u.aktif===false?"selected":""}>Nonaktif</option></select></div></div><div class="actions"><button class="btn primary">Simpan</button></div></form>`);$("editUser").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);await updateDoc(doc(db,"users",id),{nama:f.get("nama"),email:f.get("email"),role:f.get("role"),aktif:f.get("aktif")==="true",updatedAt:serverTimestamp()});closeModal();toast("Pengguna diperbarui");renderUsers()}}
function scanBarcode(callback){openModal(`<h2>Scan Barcode</h2><div id="reader" style="width:100%"></div><p class="small">Izinkan akses kamera. Fitur membutuhkan HTTPS.</p>`);let qr=new Html5Qrcode("reader");qr.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:150}},code=>{qr.stop().catch(()=>{});closeModal();callback(code)},()=>{}).catch(e=>{$("reader").innerHTML="<p class='error'>Kamera tidak dapat dibuka. Pastikan browser mengizinkan kamera dan situs menggunakan HTTPS.</p>"})}

onAuthStateChanged(auth,async user=>{if(!user){$("loginPage").classList.remove("hidden");$("appPage").classList.add("hidden");return}try{let s=await getDoc(doc(db,"users",user.uid));if(!s.exists()||s.data().aktif!==true){await signOut(auth);$("loginError").textContent="Akun belum terdaftar/aktif.";return}currentUser=user;currentProfile=s.data();$("loginPage").classList.add("hidden");$("appPage").classList.remove("hidden");$("userName").textContent=(currentProfile.nama||user.email)+" ("+(currentProfile.role||"")+")";document.querySelectorAll(".admin-only").forEach(x=>x.style.display=currentProfile.role==="admin"?"":"none");nav("dashboard")}catch(e){await signOut(auth);$("loginError").textContent="Profil pengguna tidak dapat dibaca."}});
